[GeneralConfig]
    NetworkAddress = "https://node.testnet.klever.org" # the network address
    PrivateKeyFile = "keys/oracle.pem" # the path to the pem file containing the relayer klever blockchain wallet allowed to write to contract
    IntervalToResendTxsInSeconds = 60 # the time in seconds between nonce reads
    ProxyCacherExpirationSeconds = 600 # the caching time in seconds
    AggregatorContractAddress = "klv1qqqqqqqqqqqqqpgqvzsgch5appevk26vuz3w6cwp2mh84ugsk3cs4pvvqn" # aggregator contract address
    BaseGasLimit = 25000000 # base gas limit
    GasLimitForEach = 2000000 # gas limit for each fetcher
    MinResultsNum = 3 # min number of results waiting
    PollIntervalInSeconds = 2 # polling interval for fetchers
    AutoSendIntervalInSeconds = 30 # seconds before next send price when percent difference is not met

    # valid options for ProxyRestAPIEntityType are `observer` and `proxy`. Any other value will trigger an error.
    # `observer` is useful when querying an observer, directly and `proxy` is useful when querying a squad's proxy
    ProxyRestAPIEntityType = "observer"
    ProxyFinalityCheck = false
    ProxyMaxNoncesDelta = 7 # the number of maximum blocks allowed to be "in front" of what the metachain has notarized

[Logs]
    LogFileLifeSpanInSec = 86400 # 24h
    LogFileLifeSpanInMB = 1024 # 1GB

[AuthenticationConfig]
    TokenExpiryInSeconds = 86400 # 24h
    Host = "oracle"

# Each pair has a specific list of exchanges from where the price can be fetched
# This list must be in respect with the implemented fetchers names:
# "Binance", "Bitfinex", "Crypto.com", "Gemini", "HitBTC", "Huobi", "Kraken", "Okex"
[[Pairs]]
    Base = "ETH"
    Quote = "USD"
    PercentDifferenceToNotify = 1 # percent difference to notify price change. 0 notifies for each change
    Decimals = 4 # decimals for prices
    Exchanges = ["Binance", "Bitfinex", "Crypto.com", "Gemini", "Huobi", "Kraken", "Okx"]

# Each pair has a specific list of exchanges from where the price can be fetched
# This list must be in respect with the implemented fetchers names:
# "Binance", "Bitfinex", "Crypto.com", "Gemini", "HitBTC", "Huobi", "Kraken", "Okex"
# The base value is always ETH, which means it will quote the value of 1 GWEI in the quote currency
[[GasStationPair]]
    Quote = "USD"
    PercentDifferenceToNotify = 1 # percent difference to notify price change. 0 notifies for each change
    Decimals = 9 # decimals for prices
    Exchanges = ["EVM gas price station when using selector SafeGasPrice"]
# XExchange token ids mappings
# This should be a mapping between the above generic symbols pairs and their xExchange token ids equivalents
# The key in map must be uppercase and tokens should be separated by "-"
# All available pairs can be found at https://api.multiversx.com/mex-pairs
# egs.
#   "ETH-USD"
#       Base  = "ETH-tbd000"   -> placeholder, not added yet
#       Quote = "USDC-c76f1f"
#   "EGLD-USD"
#       Base  = "WEGLD-bd4d79"
#       Quote = "USDC-c76f1f"
